
CREATE TABLE DBAMDATA.T684_LOG_IMPORTACAO_PRODUTO
(
 T684_UNIDADE            NUMBER(3),
 T684_PRODUTO            NUMBER(6),
 T684_DESCRICAO          VARCHAR2(80),
 T684_DATA_PROCESSAMENTO DATE,
 T684_NOME_ARQUIVO       VARCHAR2(100),
 T684_LINHA_VALIDA       VARCHAR2(3),
 T684_ERRO               VARCHAR2(1000),
 T684_NOME_CAMPO         VARCHAR2(50),
 T684_VALOR_ANTERIOR     VARCHAR2(100),
 T684_VALOR_ATUAL        VARCHAR2(100),
 T684_USUARIO            NUMBER(4),
 T684_LINHA_ARQUIVO      NUMBER(6)
) TABLESPACE TSD_DBAMDATA;
CREATE PUBLIC SYNONYM T684_LOG_IMPORTACAO_PRODUTO FOR DBAMDATA.T684_LOG_IMPORTACAO_PRODUTO;
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMDATA.T684_LOG_IMPORTACAO_PRODUTO TO MDLOG;
GRANT DELETE, INSERT, SELECT, UPDATE ON DBAMDATA.T684_LOG_IMPORTACAO_PRODUTO TO MEDI;
GRANT SELECT, UPDATE, DELETE, INSERT ON DBAMDATA.T684_LOG_IMPORTACAO_PRODUTO TO INFOMLOG;
CREATE GLOBAL TEMPORARY TABLE INFOMLOG.RCAD_EXPORTACAO_PRODUTO
(
 RCAD_UNIDADE             NUMBER(3),
 RCAD_PRODUTO             NUMBER(6),
 RCAD_DESCRICAO           VARCHAR2(20),
 RCAD_MARCA               VARCHAR2(30),
 RCAD_APRESENTACAO        VARCHAR2(20),
 RCAD_NCM                 VARCHAR2(8),
 RCAD_ORIGEM              VARCHAR2(60),
 RCAD_CEST                VARCHAR2(7),
 RCAD_PRODUTO_ATIVO       VARCHAR2(3),
 RCAD_DESCONTINUADO       VARCHAR2(3),
 RCAD_DT_DESCONTINUADO    DATE,
 RCAD_DATA_CADASTRO       DATE,
 RCAD_DATA_ATIVACAO       DATE,
 RCAD_ESTOCADO            VARCHAR2(3),
 RCAD_FORNECEDOR_ESTOCADO VARCHAR2(50),
 RCAD_FORNECEDOR_PRODUTO  VARCHAR2(50),
 RCAD_TIPO_FORNECEDOR     VARCHAR2(10), 
 RCAD_CNPJ_FORNECEDOR     VARCHAR2(14),
 RCAD_UF_FORNECEDOR       VARCHAR2(2),
 RCAD_COMPRADOR           VARCHAR2(45)
) ON COMMIT PRESERVE ROWS;
CREATE PUBLIC SYNONYM RCAD_EXPORTACAO_PRODUTO FOR INFOMLOG.RCAD_EXPORTACAO_PRODUTO;
GRANT UPDATE, SELECT, INSERT, DELETE ON RCAD_EXPORTACAO_PRODUTO TO MDLOG, MEDI;
CREATE GLOBAL TEMPORARY TABLE INFOMLOG.RCAD_IMPORTACAO_PRODUTO
(
 RCAD_UNIDADE         NUMBER(3),
 RCAD_PRODUTO         NUMBER(6),
 RCAD_DESCRICAO       VARCHAR2(80),
 RCAD_ORIGEM          CHAR(1),
 RCAD_TEM_IPI         CHAR(1), 
 RCAD_ALIQUOTA_IPI    NUMBER(4,2),
 RCAD_TIPO_IPI        CHAR(1),
 RCAD_VALOR_IPI       NUMBER(15,2),
 RCAD_CONVENIO        CHAR(1), 
 RCAD_PART_DECEST     CHAR(1),  
 RCAD_COD_DECRETO     VARCHAR2(4),
 RCAD_DT_ATIVACAO_DEC DATE,
 RCAD_OBJ_VENDA       NUMBER(11,3),
 RCAD_MARGEM          NUMBER(6,3),    
 RCAD_TEMPO           NUMBER(2),
 RCAD_CEST            VARCHAR2(7),
 RCAD_LINHA_ARQUIVO   NUMBER(6)
) ON COMMIT PRESERVE ROWS;
CREATE PUBLIC SYNONYM RCAD_IMPORTACAO_PRODUTO FOR INFOMLOG.RCAD_IMPORTACAO_PRODUTO;
GRANT UPDATE, SELECT, INSERT, DELETE ON RCAD_IMPORTACAO_PRODUTO TO MDLOG, MEDI;
