
DROP PUBLIC SYNONYM T684_LOG_IMPORTACAO_PRODUTO;
DROP TABLE DBAMDATA.T684_LOG_IMPORTACAO_PRODUTO;
DROP PUBLIC SYNONYM RCAD_EXPORTACAO_PRODUTO;
DROP TABLE INFOMLOG.RCAD_EXPORTACAO_PRODUTO;
DROP PUBLIC SYNONYM RCAD_IMPORTACAO_PRODUTO;
DROP TABLE INFOMLOG.RCAD_IMPORTACAO_PRODUTO;
