
/*************************************************************************************
Schema       : DBAMDATA
Analista     : Lenilton Marques
Data         : 30 de outubro de 2018
Descricao    : Criação de campos no cadastro de configurações de impostos
CRC          : 75386
**************************************************************************************/
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_DESC_ITEM           ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_DESC_REPASSE        ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_DESC_COMERCIAL      ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_DESCDESP_EMBALAGEM  ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_ADICDESP_ACESSORIAS ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_ADICVALOR_IPI       ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_DESC_ITEM           ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_DESC_REPASSE        ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_DESC_COMERCIAL      ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_DESCDESP_EMBALAGEM  ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_ADICDESP_ACESSORIA  ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_ADICVALOR_IPI       ;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_PIS_ORIGEM_COMPRA;
ALTER TABLE DBAMDATA.T274_TIPOS_OPERACAO_FISCAL DROP COLUMN T274_COFINS_ORIGEM_COMPRA;
ALTER TABLE DBAMDATA.T073_ENTRADA DROP COLUMN T073_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T073_ENTRADA DROP COLUMN T073_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T073_ENTRADA DROP COLUMN T073_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T073_ENTRADA DROP COLUMN T073_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T073_ENTRADA DROP COLUMN T073_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T073_ENTRADA DROP COLUMN T073_BASE_COFINS_NORMAL;
ALTER TABLE DBAMDATA.T074_ENTRADA_ALIQUOTA DROP COLUMN T074_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T074_ENTRADA_ALIQUOTA DROP COLUMN T074_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T074_ENTRADA_ALIQUOTA DROP COLUMN T074_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T074_ENTRADA_ALIQUOTA DROP COLUMN T074_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T074_ENTRADA_ALIQUOTA DROP COLUMN T074_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T074_ENTRADA_ALIQUOTA DROP COLUMN T074_BASE_COFINS_NORMAL;
ALTER TABLE DBAMDATA.T078_ENTRADA_ITENS DROP COLUMN T078_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T078_ENTRADA_ITENS DROP COLUMN T078_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T078_ENTRADA_ITENS DROP COLUMN T078_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T078_ENTRADA_ITENS DROP COLUMN T078_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T078_ENTRADA_ITENS DROP COLUMN T078_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T078_ENTRADA_ITENS DROP COLUMN T078_BASE_COFINS_NORMAL;
ALTER TABLE DBAMDATA.T209_LOTESTOQUE DROP COLUMN T209_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T209_LOTESTOQUE DROP COLUMN T209_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T209_LOTESTOQUE DROP COLUMN T209_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T209_LOTESTOQUE DROP COLUMN T209_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T209_LOTESTOQUE DROP COLUMN T209_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T209_LOTESTOQUE DROP COLUMN T209_BASE_COFINS_NORMAL;
ALTER TABLE DBAMDATA.T210_LOTESTOQUE_ALIQUOTA DROP COLUMN T210_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T210_LOTESTOQUE_ALIQUOTA DROP COLUMN T210_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T210_LOTESTOQUE_ALIQUOTA DROP COLUMN T210_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T210_LOTESTOQUE_ALIQUOTA DROP COLUMN T210_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T210_LOTESTOQUE_ALIQUOTA DROP COLUMN T210_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T210_LOTESTOQUE_ALIQUOTA DROP COLUMN T210_BASE_COFINS_NORMAL;
ALTER TABLE DBAMDATA.T211_LOTESTOQUE_ITENS DROP COLUMN T211_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T211_LOTESTOQUE_ITENS DROP COLUMN T211_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T211_LOTESTOQUE_ITENS DROP COLUMN T211_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T211_LOTESTOQUE_ITENS DROP COLUMN T211_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T211_LOTESTOQUE_ITENS DROP COLUMN T211_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T211_LOTESTOQUE_ITENS DROP COLUMN T211_BASE_COFINS_NORMAL;
ALTER TABLE DBAMDATA.T124_SAIDA_ICMS DROP COLUMN T124_BASE_PIS_ISENTO;
ALTER TABLE DBAMDATA.T124_SAIDA_ICMS DROP COLUMN T124_BASE_PIS_RETIDO;
ALTER TABLE DBAMDATA.T124_SAIDA_ICMS DROP COLUMN T124_BASE_PIS_NORMAL;
ALTER TABLE DBAMDATA.T124_SAIDA_ICMS DROP COLUMN T124_BASE_COFINS_ISENTO;
ALTER TABLE DBAMDATA.T124_SAIDA_ICMS DROP COLUMN T124_BASE_COFINS_RETIDO;
ALTER TABLE DBAMDATA.T124_SAIDA_ICMS DROP COLUMN T124_BASE_COFINS_NORMAL;
ALTER TABLE INFOMLOG.TNOT4_CALCULO_NOTA_ICMS DROP COLUMN TNOT4_BASE_PIS_ISENTO;
ALTER TABLE INFOMLOG.TNOT4_CALCULO_NOTA_ICMS DROP COLUMN TNOT4_BASE_PIS_RETIDO;
ALTER TABLE INFOMLOG.TNOT4_CALCULO_NOTA_ICMS DROP COLUMN TNOT4_BASE_PIS_NORMAL;
ALTER TABLE INFOMLOG.TNOT4_CALCULO_NOTA_ICMS DROP COLUMN TNOT4_BASE_COFINS_ISENTO;
ALTER TABLE INFOMLOG.TNOT4_CALCULO_NOTA_ICMS DROP COLUMN TNOT4_BASE_COFINS_RETIDO;
ALTER TABLE INFOMLOG.TNOT4_CALCULO_NOTA_ICMS DROP COLUMN TNOT4_BASE_COFINS_NORMAL;
