
CREATE PUBLIC SYNONYM PCAD_EXPORTACAO_PRODUTO FOR INFOMLOG.PCAD_EXPORTACAO_PRODUTO;
GRANT EXECUTE ON INFOMLOG.PCAD_EXPORTACAO_PRODUTO TO MDLOG;
CREATE PUBLIC SYNONYM PCAD_IMPORTACAO_PRODUTO FOR INFOMLOG.PCAD_IMPORTACAO_PRODUTO; 
GRANT EXECUTE ON INFOMLOG.PCAD_IMPORTACAO_PRODUTO TO MDLOG;
