
CREATE PUBLIC SYNONYM PACK_IMPOSTOS FOR INFOMLOG.PACK_IMPOSTOS;
CREATE PUBLIC SYNONYM PFIS_CALCULO_PIS_COFINS FOR INFOMLOG.PFIS_CALCULO_PIS_COFINS;
GRANT EXECUTE ON INFOMLOG.PACK_IMPOSTOS TO MDLOG;
GRANT EXECUTE ON INFOMLOG.PACK_IMPOSTOS TO INTEGRA;
GRANT EXECUTE ON INFOMLOG.PFIS_CALCULO_PIS_COFINS TO MDLOG;
GRANT EXECUTE ON INFOMLOG.PFIS_CALCULO_PIS_COFINS TO INTEGRA;
