
BEGIN
  UPDATE INTEGRA.TI049_OBJETOS_INTEGRA_CAMPOS             
     SET TI049_CAMPO_CALCULADO = 'N'
   WHERE TI049_CODIGO_OBJETO_IE = 'T128_SAIDA_ITENS'
     AND TI049_CODIGO_OBJETO_INTEGRA_IE = 'TI042_NF_SAIDA_PRODUTOS'
     AND TI049_CAMPO_ORIGEM_DESTINO = 'TI042_DESCONTO_BONIFICACAO';     
  UPDATE INTEGRA.TI049_OBJETOS_INTEGRA_CAMPOS             
     SET TI049_CAMPO_CALCULADO = 'N'
   WHERE TI049_CODIGO_OBJETO_IE = 'T128_SAIDA_ITENS'
     AND TI049_CODIGO_OBJETO_INTEGRA_IE = 'TI042_NF_SAIDA_PRODUTOS'
     AND TI049_CAMPO_ORIGEM_DESTINO = 'TI042_DESCONTO_BRINDE';     
  DELETE FROM INTEGRA.TI058_CAMPO_VALOR
   WHERE TI058_OBJETO_IE = 'T128_SAIDA_ITENS'   
     AND TI058_CAMPO_IE = 'T128_DESCONTO_BONIFICACAO';          
  DELETE FROM INTEGRA.TI057_CAMPO
   WHERE TI057_OBJETO_IU = 'T128_SAIDA_ITENS'
     AND TI057_CAMPO_IU = 'T128_DESCONTO_BONIFICACAO';
  DELETE FROM INTEGRA.TI058_CAMPO_VALOR
   WHERE TI058_OBJETO_IE = 'T128_SAIDA_ITENS'   
     AND TI058_CAMPO_IE = 'T128_DESCONTO_BRINDE';     
  DELETE FROM INTEGRA.TI057_CAMPO
   WHERE TI057_OBJETO_IU = 'T128_SAIDA_ITENS'
     AND TI057_CAMPO_IU = 'T128_DESCONTO_BRINDE';                   
  DELETE FROM INTEGRA.TI062_CADASTRO_SCRIPT_PARAM
        WHERE TI062_CODIGO_SCRIPT_IE = 400;                  
  DELETE FROM INTEGRA.TI061_CADASTRO_SCRIPT
        WHERE TI061_CODIGO_SCRIPT_IU = 400;        
  COMMIT;
END;
/
